# Generated by Django 5.0.6 on 2024-06-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectJensen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProjectJensen.equipo'),
        ),
    ]
